# Generated by Django 3.1.5 on 2021-01-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_auto_20210123_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmers.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
