# Generated by Django 3.1.5 on 2021-01-23 22:28

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_auto_20210123_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmers.sellerprofile')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmers.userprofile')),
            ],
        ),
    ]
