# Generated by Django 3.1.5 on 2021-01-24 07:21

import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_auto_20210123_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.AddField(
            model_name='inventory',
            name='latitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='longitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='when',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location'),
        ),
    ]
