# Generated by Django 3.1.5 on 2021-01-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0014_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='keyword',
            field=models.CharField(default='', max_length=20),
        ),
    ]
